# @format

title: Awesome DesignOps
description: A comprehensive guide to DesignOps concepts, principles, practices and tools for Early Stage Startups
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
    Template Repository: https://github.com/just-the-docs/just-the-docs-template
